### ISSUE TITLE
Small porblems about using ethsema

### ISSUE THREAD

**Issue by q871795224** [ethsema/ethsema#4]
I'm working on some projects about Ethereum smart contract detection in ewasm. I was pleasantly surprised to find  ethsema. However, when I use ethsema, I find some porblems. I have no idea if this is a bug or feature.

The commands and tools I use are as follows
solc: 0.8.12+commit.f00d7308.Linux.g++, to compile sol to bin
vscode:  plugin WebAssembly v1.3.1 , to view the wasm file
cmd:
```
# use solc to compile sol
solc -o /mnt/d/workspace/ethsema_test --bin --overwrite /mnt/d/workspace/ethsema_test/reEntrancy.sol
# use ethsema to change .bin to wasm
cat /mnt/d/workspace/ethsema_test/reEntrancy.bin | xxd -r -ps > /mnt/d/workspace/ethsema_test/reEntrancy_.bin && /mnt/d/code/blockchain/ethsema-main/standalone-evmtrans /mnt/d/workspace/ethsema_test/reEntrancy_.bin -o /mnt/d/workspace/ethsema_test/reEntrancy.wasm
```

when I use ethsema to compile reEntrancy.sol in example, Its result is shown like below:
```solidity
pragma solidity ^0.8.11;

contract reEntrancy {
  mapping(address => uint256) public balances;

  constructor(uint256 airtoken){
    balances[msg.sender] = airtoken;
  }

  function depositFunds() public payable {
      balances[msg.sender] += msg.value;
  }
  function withdrawFunds (uint256 _weiToWithdraw) public payable {
    require(balances[msg.sender] >= _weiToWithdraw);
    (bool success, ) = msg.sender.call{value: _weiToWithdraw, gas:gasleft()}(abi.encodeWithSignature("any()") );
    require(success);
    unchecked { 
        balances[msg.sender] -= _weiToWithdraw;
    }
    }
}
```
![image](https://user-images.githubusercontent.com/33190881/160635130-1b961a41-9e61-4865-b0ec-ce86d02eb388.png)
everything looks good

However, when I delete some code of the contract, like this
```solidity
pragma solidity ^0.8.11;

contract reEntrancy {
  mapping(address => uint256) public balances;

  constructor(uint256 airtoken){
    balances[msg.sender] = airtoken;
  }

  function depositFunds() public payable {
      balances[msg.sender] += msg.value;
  }
  function withdrawFunds (uint256 _weiToWithdraw) public payable {
    (bool success, ) = msg.sender.call{value: _weiToWithdraw, gas:gasleft()}(abi.encodeWithSignature("any()") );
    }
}
```
 The wasm like this: It looks like have no difference
![image](https://user-images.githubusercontent.com/33190881/160636380-8fc15085-6a53-4d6b-80ef-94a12db2ea8b.png)
 
When I delete further, like this:
```solidity
pragma solidity ^0.8.11;

contract reEntrancy {
  mapping(address => uint256) public balances;

  constructor(uint256 airtoken){
    balances[msg.sender] = airtoken;
  }
}
```
the result like this: also looks no difference
![image](https://user-images.githubusercontent.com/33190881/160637031-7eb88c38-f486-4c9a-9a02-dac147ef425e.png)

I delete almost everything
```solidity
pragma solidity ^0.8.11;

contract reEntrancy {
  mapping(address => uint256) public balances;
}
```
the result seems more normal
![image](https://user-images.githubusercontent.com/33190881/160637616-da31ffb9-d536-4d27-b4f2-418587d1a3bc.png)

So I try to add something, but delete constructor
```solidity
pragma solidity ^0.8.11;

contract reEntrancy {
  mapping(address => uint256) public balances;

  function depositFunds() public payable {
      balances[msg.sender] += msg.value;
  }
  function withdrawFunds (uint256 _weiToWithdraw) public payable {
    require(balances[msg.sender] >= _weiToWithdraw);
    (bool success, ) = msg.sender.call{value: _weiToWithdraw, gas:gasleft()}(abi.encodeWithSignature("any()") );
    require(success);
    unchecked { 
        balances[msg.sender] -= _weiToWithdraw;
    }
    }
}
```
the result make me confuse.
![image](https://user-images.githubusercontent.com/33190881/160637944-651880cf-81da-4adf-9d88-fda98e989572.png)

What am I doing wrong? Or maybe vscode plugin WebAssembly display error？ Or other reasons.
I look forward to your reply. I really like ethsema

By the way, I see Chinese in the display gif, can we communicate in Chinese？

**Comment by ethsema-mirror** [comment]
Thank you for your interest in EthSema. I can run your example at an ewasm testnet, e.g., executing its public functions. 
More technical details will be discussed after our paper is accepted.
